sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "stable"
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - npm run ci:coveralls
  - npm run ci:release
branches:
  only:
    - master
