sudo: required
language: node_js
services:
  - docker
env:  
  global:
    - DOCKER_VERSION=1.11.2
    - DOCKER_COMPOSE_VERSION=1.7.1
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "stable"
before_script:
  - npm prune
script:
  - npm test
  - docker-compose -v
  - docker-compose config
  - npm run docker-test-integration
  - npm run build
after_success:
  - npm run ci:coveralls
  - npm run ci:release
branches:
  only:
    - master
    - ci
